### ISSUE TITLE
Improve & standardise metadata in the output files.

### ISSUE THREAD

**Issue by g-kimbell** [dgbowl/tomato#85] opened 2024-05-29 07:51 UTC
On 0.2.x by default the sample name is not recorded in snapshot or final files

It could also be useful to record the channel and address used in the final file metadata

**Comment by PeterKraus** [comment] 2024-07-17 11:49
Yup, we ought to provide more provenance info. Some tomato-specific metadata, pipeline information, sample information and the settings from the `Payload` should be stored in the toplevel node of the returned `DataTree`; the task lists can be stored in the groups (i.e. per-component).

**Comment by PeterKraus** [comment] 2024-11-19 19:09
Issue #106 is a duplicate of this.

**Closed** 2024-11-20 13:55 UTC
